### ISSUE TITLE
1.12 - Compression Trouble

### ISSUE THREAD

**Issue by Darkosto** [CJ-MC-Mods/IBHSTD#24]
Hello! 

I seem to be having some trouble with adding blocks to compression:

            minecraft:cobblestone:8:true
            minecraft:obsidian:8:true
            minecraft:netherrack:8:true
            minecraft:dirt:8:true
            minecraft:gravel:8:true

I used the 1.11.2 entries but when I open up JEI they don't seem to exist. Is there something I might be doing incorrectly? 

#### Overloaded Version: 0.0.29

Thank you very much!
Darkosto

**Comment by cjm721** [comment]
I removed that feature in 1.12 and it's low priority to add back.

**Comment by Darkosto** [comment]
Okay, thanks for the quick response.

**Comment by cjm721** [comment]
If you reset your config that section goes away.

**Comment by Darkosto** [comment]
Alright, I'll do a config reset. Thanks for your time.

**Comment by kohlth** [comment]
(Creeps in back ) hmm look darkesto messing with overloaded how interesting

**Comment by cjm721** [comment]
If there is enough interest will consider moving it back up. It got pushed down only because of all the recipe changes in 1.12 and I knew I was going to be doing custom recipe stuff latter so decided just to combine those two sections since it did not seem to be nearly as simple as it had before. 

Also wanted to update how I was doing it so I was not taking up so much of the Block ID map (4096 Cap) without making all of them TEs.

**Comment by Darkosto** [comment]
It's honestly no worries. There's a mod that just released called "compression" that does this functionality, no need to move forward with it in your mod if it's a low priority.

**Comment by tyler489** [comment]
I wouldnt mind this feature... also hi kohlith...

**Comment by cjm721** [comment]
Compressed Blocks are back. Config options now also include hardness multiplier.
